version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: '192.168.3.39'
      environment:
        #TZ: 'Asia/Shenzhen'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.3.39'
          #gitlab_rails['time_zone'] = 'Asia/Shenzhen'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.163.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "jenkins_zeng@163.com"
          gitlab_rails['smtp_password'] = "zenghaitao9250"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = 'jenkins_zeng@163.com'
      ports:
        - '10080:80'
        - '443:443'
        - '10022:22'
      volumes:
        - /data/gitlab/config:/etc/gitlab
        - /data/gitlab/data:/var/opt/gitlab
        - /data/gitlab/logs:/var/log/gitlab
